version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-local
    restart: unless-stopped
    ports:
      - 9000:9000    # API
      - 9001:9001    # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_shop
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  spark:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spark-py:1.0
    container_name: spark-local
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ./solutions:/app
      - ./jars:/opt/extra-jars
    working_dir: /app
    # depends_on:
    #   - minio # need to add a healthcheck to minio and wait for it before starting spark.
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy

    # command: sh -c "sleep infinity"
    command: /opt/spark/bin/spark-submit --master local[*] test.py
    # command: /opt/spark/bin/spark-submit --master local[*] --jars /opt/extra-jars/hadoop-aws-3.3.2.jar,/opt/extra-jars/aws-java-sdk-bundle-1.12.262.jar generate_orders.py
    # command: bash -c "python3 setup_minio.py && /opt/spark/bin/spark-submit --master local[*] job1.py"
    # command: bash -c "python3 setup_minio.py && /opt/spark/bin/spark-submit --master local[*] --jars /opt/extra-jars/hadoop-aws-3.3.2.jar,/opt/extra-jars/aws-java-sdk-bundle-1.12.262.jar generate_orders.py"
    # command: /opt/spark/bin/spark-submit --master local[*] --jars /opt/extra-jars/postgresql-42.6.0.jar connect_postgres.py
    # command: /opt/spark/bin/spark-submit --master local[*] --jars /opt/extra-jars/postgresql-42.6.0.jar,/opt/extra-jars/hadoop-aws-3.3.2.jar,/opt/extra-jars/aws-java-sdk-bundle-1.12.262.jar dj_customer_retention_pipeline.py
    # command: /opt/spark/bin/spark-submit --master local[*] --jars /opt/extra-jars/postgresql-42.6.0.jar,/opt/extra-jars/hadoop-aws-3.3.2.jar,/opt/extra-jars/aws-java-sdk-bundle-1.12.262.jar de_clv.py

